name: Deploy to production

on: 
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    name: Deploying everything to the production cluster
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: SSH and deploy using password
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no root@198.38.89.233 << 'EOF'
            cd make-songs/
            git pull origin main
            export PATH=/root/.nvm/versions/node/v22.14.0/bin:$PATH
            npm install
            npm run build
            pm2 restart vito-x
          EOF
